### ISSUE TITLE
Subscriptions not updating

### ISSUE THREAD

**Issue by peterge1998** [omarroth/invidious#1035]
Youtube;
![image](https://user-images.githubusercontent.com/47355238/74610010-b3abad80-50ef-11ea-99a6-dead665301d3.png)
My invidious instance:
![image](https://user-images.githubusercontent.com/47355238/74610025-db9b1100-50ef-11ea-9ac3-d8ceb9bf6cb3.png)

I read that full_refresh might cause this. Would setting this to true solve it?
And whats the default intervall to check the rss feeds?

```
channel_threads: 1
feed_threads: 1
db:
  user: username
  password: password
  host: 172.20.0.81
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:
```
