### ISSUE TITLE
Non stop high CPU Usage

### ISSUE THREAD

**Issue by ewdissi** [omarroth/invidious#225]
Hi,

i've created an virtual server for invidious. It works ok so far, but why is the cpu utilization always at 80%?
Is Invidious non stop crawling youtube? Why you can't create a index one time?

Regards
Dissi

![invidious](https://user-images.githubusercontent.com/44837549/48181430-ba157c00-e327-11e8-9509-65cae6755a97.png)

**Comment by omarroth** [comment]
I'd recomend taking a look through the `config/config.yml` file and disabling parts that you don't need. 
```yml
crawl_threads: 1
channel_threads: 1
feed_threads: 1
video_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
geo_bypass: true
```
Likely the biggest source of CPU would be the `geo_bypass`, since it works by building up a list of proxies. Most users won't ever see it, so you can probably disable it.

The crawlers are explained more in depth [here](https://github.com/omarroth/invidious#usage), but I doubt you need many of them. In fact, I'll probably set the default for `crawl_threads` and `video_threads` to 0, since they arguably aren't useful at all and use up CPU.

I'm unfortunately not sure quite what you mean by "create a index one time", you'll have to clarify there.

**Comment by alexvelin** [comment]
Hey. I have exactly the same problem. The processor is constantly used by at least 60%. I use Docker. My `config/config.yml` looks like this:
```yaml
video_threads: 0
crawl_threads: 0
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
geo_bypass: false
```
