### ISSUE TITLE
Make landing page configurable

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#295]
Add the ability to configure the landing page. Admin of instances should be able to configure the default one. For example I want to set "TRENDING" as default landing page.

**Comment by omarroth** [comment]
See also #227. I expect to add it to preferences as well so users can do the same.

**Comment by omarroth** [comment]
Added for administrators with a39b1583dacff31664830fd4f8966014f8869fa0. Before I close this I'd also like to add an option for regular users to configure their landing page/feeds.

**Comment by omarroth** [comment]
Added configurable menu per user with 7524b5e349ca403d49d4c35c55e9dc161a4e7d59. Important to note is that this change moves `default_home` and `feed_menu` into `default_user_preferences`.

For example:

```yaml
default_home: Top
feed_menu:
  - Top
  - Popular
```

Becomes:

```yaml
default_user_preferences:
  default_home: Top
  feed_menu:
    - Top
    - Popular
```
