### ISSUE TITLE
Login/Register broken?

### ISSUE THREAD

**Issue by gerroon** [omarroth/invidious#304]
HI

I just did docker compose, I open the page try to register with clock, it says invalid answer, it is not invalid I put the right time values there.

So I do text captcha, it pretends it does but when I try to login with the so called registered user name, nothing happens, after answering the captcha.

I do not get  what is going here  :( Is there a default admin that I can login and add myself?

I do not have a Google account so I cant use that.

Btw I do not care about Youtube account specific stuff, I just want to be able to customize the ui according to my login.

**Comment by knightfallx66** [comment]
I'm having this exact same issue with the latest build.

**Comment by sunnythaper** [comment]
Having the exact same issue as well. Also in my logs I keep seeing "Index out of bounds" over and over again. Not sure if the two are related.

**Comment by gerroon** [comment]
I am not sure what am I supposed to do there. This is how the defaults are in the file

```
config.yml                                                                                                                                                                        buffers 
  video_threads: 0                                                                                                                                                                            
  crawl_threads: 0                                                                                                                                                                            
  channel_threads: 1                                                                                                                                                                          
  feed_threads: 1                                                                                                                                                                             
  db:                                                                                                                                                                                         
    user: kemal                                                                                                                                                                               
    password: kemal                                                                                                                                                                           
    host: localhost                                                                                                                                                                           
    port: 5432                                                                                                                                                                                
    dbname: invidious                                                                                                                                                                         
  full_refresh: false                                                                                                                                                                         
  https_only: false           


```
