### ISSUE TITLE
Add option to configure default user preferences

### ISSUE THREAD

**Issue by Perflyst** [omarroth/invidious#415]
At the moment there is no configuration option to set the default preferences for your instance via config.yml
It would be nice to see something to set defaults for preferences which are available at https://invidio.us/preferences

**Comment by omarroth** [comment]
Added with bd4f5ebcdfb2e4bcbe7872fc76cdbf26e7dd4f80, usage looks like:
```yaml
# ...
default_user_preferences:
  dark_mode: true
  local: true
  locale: "en-US"
  comments: ["youtube",""]
# ...
```

Any changes are applied to [these defaults](https://github.com/omarroth/invidious/blob/master/src/invidious/helpers/helpers.cr#L39).
