### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by johnwmail** [omarroth/invidious#426]
HI, how to fix high cpu usage problem, like this
https://github.com/omarroth/invidious/issues/225
Thanks.

**Comment by omarroth** [comment]
Hi! Would you mind providing your `config/config.yml` file and the branch you're using?

**Comment by johnwmail** [comment]
Hi, basically I am following "Installation" on https://github.com/omarroth/invidious
my system is debian/amd64/sid, and I think it is master branch (is it?),
"git clone https://github.com/omarroth/invidious"
config/config.yml:
video_threads: 0
crawl_threads: 0
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:

Sorry, I do not know how to debug, thanks.

**Comment by omarroth** [comment]
I've done a little more work improving performance, so you might update and see if CPU usage has improved for you.

**Comment by johnwmail** [comment]
Hi, I tried this morning, still very high cpu usage,
but I noticed the high cpu usage is postgres, not invidious itselt.
(But the postgres only for invidios)
ps aux

<pre>
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   7900   972 pts/0    Ss+  04:08   0:00 init [2]
root       642  0.0  0.1   8152  4984 ?        Ss   06:19   0:00 bash -l
postgres  4093  0.0  0.6 213760 27512 ?        S    06:21   0:00 /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/postgresql.conf
postgres  4095  0.0  0.2 213888  9312 ?        Ss   06:21   0:00 postgres: 11/main: checkpointer   
postgres  4096  0.0  0.1 213900  5940 ?        Ss   06:21   0:00 postgres: 11/main: background writer   
postgres  4097  0.0  0.2 213760  9756 ?        Ss   06:21   0:00 postgres: 11/main: walwriter   
postgres  4098  0.0  0.1 214332  6580 ?        Ss   06:21   0:00 postgres: 11/main: autovacuum launcher   
postgres  4099  0.0  0.0  68812  4140 ?        Ss   06:21   0:00 postgres: 11/main: stats collector   
postgres  4100  0.0  0.1 214188  6828 ?        Ss   06:21   0:00 postgres: 11/main: logical replication launcher   
root      7184  0.0  0.0  10300  3688 ?        S    06:23   0:00 sudo -i -u invidious
invidio+  7185  0.0  0.1   8368  5084 ?        S    06:23   0:00 -bash
invidio+  8505 21.9  0.8 175880 35652 ?        Rl+  06:59   0:41 ./invidious -b 0.0.0.0
root      8531  0.0  0.1   8188  4772 ?        Ss   07:00   0:00 bash -l
postgres  8546  171  0.3 214948 16776 ?        Rs   07:02   0:13 postgres: 11/main: kemal invidious 127.0.0.1(35860) PARSE
root      8548  0.0  0.0  10968  3148 ?        R+   07:02   0:00 ps aux
</pre>

**Comment by johnwmail** [comment]
Hi, after running few minutes, the cpu usage go down, thanks

<pre>USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   7900   972 pts/0    Ss+  04:08   0:00 init [2]
root       642  0.0  0.1   8152  4984 ?        Ss   06:19   0:00 bash -l
postgres  4093  0.0  0.6 213760 27512 ?        S    06:21   0:00 /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/postgresql.conf
postgres  4095  0.0  0.2 213888  9312 ?        Ss   06:21   0:00 postgres: 11/main: checkpointer   
postgres  4096  0.0  0.1 213900  5940 ?        Ss   06:21   0:00 postgres: 11/main: background writer   
postgres  4097  0.0  0.2 213760  9756 ?        Ss   06:21   0:00 postgres: 11/main: walwriter   
postgres  4098  0.0  0.1 214332  6580 ?        Ss   06:21   0:00 postgres: 11/main: autovacuum launcher   
postgres  4099  0.0  0.0  68812  4140 ?        Ss   06:21   0:00 postgres: 11/main: stats collector   
postgres  4100  0.0  0.1 214188  6828 ?        Ss   06:21   0:00 postgres: 11/main: logical replication launcher   
root      7184  0.0  0.0  10300  3688 ?        S    06:23   0:00 sudo -i -u invidious
invidio+  7185  0.0  0.1   8368  5084 ?        S    06:23   0:00 -bash
invidio+  8570  3.9  0.9 181684 40424 ?        Sl+  07:04   0:07 ./invidious -b 0.0.0.0
postgres  8581  0.0  0.4 215292 18708 ?        Ss   07:05   0:00 postgres: 11/main: kemal invidious 127.0.0.1(36234) idle
root      8583  0.0  0.1   8188  4684 ?        Ss   07:06   0:00 bash -l
root      8596  0.0  0.0  10968  3144 ?        R+   07:08   0:00 ps aux
</pre>

**Comment by tmiland** [comment]
CPU Usage is back up again. 

CPU load averages: | 1.67 (1 mins) , 1.68 (5 mins) , 1.66 (15 mins)
-- | --

ID | Owner | CPU | Command
-- | -- | -- | --
15675 | invidious | 46.6 % | /home/invidious/invidious/invidious -o invidious.log

**Config.yml:**

```
---
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: 
  host: 
  port: 5432
  dbname: invidious
full_refresh: false
https_only: true
domain: 
use_pubsub_feeds: true
hmac_key: 
use_feed_events: true
default_home: Trending
feed_menu:
- Top
- Trending
- Popular
- Subscriptions
top_enabled: true
captcha_enabled: true
login_enabled: true
registration_enabled: true
statistics_enabled: true
admins:
- 
external_port: 443
default_user_preferences:
  annotations: false
  annotations_subscribed: false
  autoplay: false
  captions:
  - 
  - 
  - 
  comments:
  - youtube
  - 
  continue: false
  continue_autoplay: true
  dark_mode: false
  latest_only: false
  listen: false
  local: false
  locale: en-US
  max_results: 40
  notifications_only: false
  quality: hd720
  redirect_feed: false
  related_videos: true
  sort: published
  speed: 1.0
  thin_mode: false
  unseen_only: false
  video_loop: false
  volume: 100
dmca_content: []
check_tables: true
cache_annotations: false
hsts: true

```
