### ISSUE TITLE
[Bug] Shorts show no playtime in Subscriptions

### ISSUE THREAD

**Issue by 2600box** [omarroth/invidious#5143]
Hello, and sorry in advance if this is a known issue or a configuration issue on my end. I have searched extensively and not found anyone else reporting this issue.

Apparently this is a bug with Invidious, according to the developer of Yattee: https://github.com/yattee/yattee/issues/850

**Description:**
Shorts in the Subscriptions tab show no length on my Invidious Instance which is version: [Docker Release v2.20241110.0](https://github.com/iv-org/invidious/releases/tag/v2.20241110.0)

Here is my Invidious instance showing no time for the Shorts:

![399077337-68957d1b-aca1-4cb9-b24f-12c737442283](https://github.com/user-attachments/assets/1558a7dc-294b-42c7-9ce7-25bc03a1ad0c)

and here is the Invidious instance of the Yattee developer showing a one minute length for the same short:

<img width="197" alt="399080783-9a26e629-f8f0-4594-9ffd-7f372d1870e5" src="https://github.com/user-attachments/assets/4c88d624-ff92-4a82-ab76-226e40a5d747" />

When I look at the api reported for that specific LTT short, it has the length there and is reported as a short in the api url. So it seems to be working as expected there. 

 `lengthSeconds":60`

https://invidious.inv.inst/api/v1/channels/UCXuqSBlHAE6Xw-yeJA0Tunw/shorts

```
{"videos":[{"type":"video","title":"I Built A Secret Gaming Room","videoId":"6uyI6s4XJLw","author":"Linus Tech Tips","authorId":"UCXuqSBlHAE6Xw-yeJA0Tunw","authorUrl":"/channel/UCXuqSBlHAE6Xw-yeJA0Tunw","authorVerified":false,"videoThumbnails":[{"quality":"maxres","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/maxres.jpg","width":1280,"height":720},{"quality":"maxresdefault","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/maxresdefault.jpg","width":1280,"height":720},{"quality":"sddefault","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/sddefault.jpg","width":640,"height":480},{"quality":"high","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/hqdefault.jpg","width":480,"height":360},{"quality":"medium","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/mqdefault.jpg","width":320,"height":180},{"quality":"default","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/default.jpg","width":120,"height":90},{"quality":"start","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/1.jpg","width":120,"height":90},{"quality":"middle","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/2.jpg","width":120,"height":90},{"quality":"end","url":"https://invidious.inv.inst/vi/6uyI6s4XJLw/3.jpg","width":120,"height":90}],"description":"","descriptionHtml":"","viewCount":64000,"viewCountText":"64K views","published":0,"publishedText":"55 years ago","lengthSeconds":60,"liveNow":false,"premium":false,"isUpcoming":true,"premiereTimestamp":0,"isNew":false,"is4k":false,"is8k":false,"isVr180":false,"isVr360":false,"is3d":false,"hasCaptions":false}
```

Thanks for any guidance or help!

<details>

<summary>Docker compose config</summary> 

```
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "10.33.33.13:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: ####
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: ####
        po_token: #####
        external_port: 443
        domain: invidious.domain.tld
        https_only: true
        registration_enabled: false
        admins: ["sloopbun"]
        captcha_enabled: true
        check_tables: true
        hsts: true
        popular_enabled: false
        login_enabled: true
        enable_user_notifications: true
        default_home: Subscriptions
        feed_menu: ["Subscriptions", "Playlists"]
        statistics_enabled: false
        hmac_key: "AePhin5aiDeoyeiK9ahy"
    healthcheck:
      test: wget -nv --tries=1 --spider https://invidious.domain.tld/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: #####
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
  ```
 
</details>

<details>

<summary> docker compose logs</summary>

```
inv_sig_helper-1  | [2025-01-16T10:00:34Z INFO  inv_sig_helper_rust] Fetching player
inv_sig_helper-1  | [2025-01-16T10:00:35Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/6e1dd460/player_ias.vflset/en_US/base.js
inv_sig_helper-1  | [2025-01-16T10:00:35Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: \s*=function\s*(\(\w\)\s*\{\s*var\s+\w=\w.split.*?\{\s*return"[a-zA-Z0-9_]+.?_w8_".*?\}\s*return\s+\w+\.join\(""\)\s*\}\s*;)
inv_sig_helper-1  | [2025-01-16T10:00:35Z INFO  inv_sig_helper_rust::player] Fixing up nsig_func_body.
inv_sig_helper-1  | [2025-01-16T10:00:35Z INFO  inv_sig_helper_rust::player] sig code: var Pok;var Wp={TL:function(D){D.reverse()},
inv_sig_helper-1  |     PX:function(D,O){D.splice(0,O)},
inv_sig_helper-1  |     Mv:function(D,O){var h=D[0];D[0]=D[O%D.length];D[O%D.length]=h}};Pok=function(D){D=D.split("");Wp.TL(D,50);Wp.PX(D,3);Wp.TL(D,20);Wp.PX(D,1);Wp.TL(D,55);Wp.PX(D,3);return D.join("")}
inv_sig_helper-1  | [2025-01-16T10:00:35Z INFO  inv_sig_helper_rust] Successfully fetched player
invidious-1       | 2025-01-16 10:00:34 UTC [info] SigHelper: Using helper at 'inv_sig_helper:12999'
invidious-1       | [production] Invidious is ready to lead at http://0.0.0.0:3000
invidious-db-1    |
invidious-db-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
invidious-db-1    |
invidious-db-1    | 2025-01-16 10:00:34.517 UTC [1] LOG:  starting PostgreSQL 14.15 (Debian 14.15-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
invidious-db-1    | 2025-01-16 10:00:34.518 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
invidious-db-1    | 2025-01-16 10:00:34.518 UTC [1] LOG:  listening on IPv6 address "::", port 5432
invidious-db-1    | 2025-01-16 10:00:34.521 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
invidious-db-1    | 2025-01-16 10:00:34.524 UTC [27] LOG:  database system was shut down at 2025-01-16 10:00:03 UTC
invidious-db-1    | 2025-01-16 10:00:34.528 UTC [1] LOG:  database system is ready to accept connections
invidious-1       | 2025-01-16 10:00:35 UTC [info] jobs: running ClearExpiredItems job
invidious-1       | 2025-01-16 10:00:35 UTC [info] jobs: ClearExpiredItems done.
invidious-1       | 2025-01-16 10:00:35 UTC [info] InstanceListRefreshJob: Done, sleeping for 30 minutes
invidious-1       | 2025-01-16 10:01:05 UTC [info] 200 GET /api/v1/trending 538.93ms
invidious-1       | 2025-01-16 10:01:35 UTC [info] 200 GET /api/v1/trending 343.34ms
invidious-1       | 2025-01-16 10:02:06 UTC [info] 200 GET /api/v1/trending 404.54ms
invidious-1       | 2025-01-16 10:02:36 UTC [info] 200 GET /api/v1/trending 376.04ms
invidious-1       | 2025-01-16 10:03:07 UTC [info] 200 GET /api/v1/trending 363.5ms
invidious-1       | 2025-01-16 10:03:37 UTC [info] 200 GET /api/v1/trending 338.39ms
invidious-1       | 2025-01-16 10:04:08 UTC [info] 200 GET /api/v1/trending 344.83ms
invidious-1       | 2025-01-16 10:04:38 UTC [info] 200 GET /api/v1/trending 395.28ms
invidious-1       | 2025-01-16 10:05:08 UTC [info] 200 GET /api/v1/trending 337.68ms
invidious-1       | 2025-01-16 10:05:39 UTC [info] 200 GET /api/v1/trending 453.42ms
invidious-1       | 2025-01-16 10:06:09 UTC [info] 200 GET /api/v1/trending 367.42ms
invidious-1       | 2025-01-16 10:06:40 UTC [info] 200 GET /api/v1/trending 396.54ms
invidious-1       | 2025-01-16 10:07:10 UTC [info] 200 GET /api/v1/trending 379.74ms
invidious-1       | 2025-01-16 10:07:41 UTC [info] 200 GET /api/v1/trending 434.24ms
invidious-1       | 2025-01-16 10:08:11 UTC [info] 200 GET /api/v1/trending 358.05ms
invidious-1       | 2025-01-16 10:08:42 UTC [info] 200 GET /api/v1/trending 337.1ms
invidious-1       | 2025-01-16 10:09:12 UTC [info] 200 GET /api/v1/trending 337.31ms
invidious-1       | 2025-01-16 10:09:42 UTC [info] 200 GET /api/v1/trending 345.36ms
  ```
  
  </details>
