### ISSUE TITLE
[Bug] Missing hash key: "videoDetails" (KeyError)

### ISSUE THREAD

**Issue by MarcS1975** [omarroth/invidious#5340]
**Describe the bug**
1) I search for videos
2) videos found
3) I clock on any video
4) grey error page comes up with lots of text

```
Title: `Missing hash key: "videoDetails" (KeyError)`
Date: `2025-06-04T19:03:03Z`
Route: `/watch?v=AgKs-eghzXs`
Version: `2025.05.17-f07859e @ (HEAD detached at v2.20250517.0)`
<details>
<summary>Backtrace</summary>
<p>
 

Missing hash key: "videoDetails" (KeyError)
  from /usr/share/crystal/src/hash.cr:1151:9 in 'dig'
  from /usr/share/crystal/src/json/any.cr:342:3 in 'extract_video_info'
  from src/invidious/videos.cr:327:10 in 'fetch_video'
  from src/invidious/videos.cr:315:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:31:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:95:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:143:11 in 'run'
  from ???

</p>
</details>

```

-->

### **My Logs**
2025-06-04 18:58:19 UTC [warn] Missing URLs for adaptive formats, falling back to other YT clients.
2025-06-04 18:58:19 UTC [error] get_video: XCrXMIhwOTo : Missing hash key: "videoDetails"
2025-06-04 18:58:19 UTC [info] 500 GET /watch?v=XCrXMIhwOTo 563.24ms

### ** My Docker Compose**
``` 
version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: CgsxT01oVDVOMmpjbyia_NO4BjIKCgJHQhIEGgAgIA%3D%3D
        po_token: MnTpJt1OMBmg5ekev8TcQAso9qHEt1CitQW37-jHZ82tpEvMYX4PbV1bjvipgr1VBsd0KEzt0bkLjlZDoVTYWuImPkDhII3XF7Pit9wIv8vEWq6nbIZKOEN4WGes6KbAmz-jDAFtlB1YJcLkcmeP1Q6s-UL3oQ==
        quality: dash
        quality_dash: 1080p
        speed: 1.5
        volume: 25
        # external_port:
        # domain:
        # https_only: false
        statistics_enabled: false
        hmac_key: "HMAC2024?"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    volumes:
      - /DockerappsHot/Invidious/db-data:/var/lib/postgresql/data
      - /DockerappsHot/Invidious/db-config:/config/sql
      - /DockerappsHot/Invidious/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: pwd
      POSTGRES_PASSWORD: pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
```
