### ISSUE TITLE
Hide cursor over video when video bar hides itself

### ISSUE THREAD

**Issue by recette-lemon** [omarroth/invidious#612]
Its a little annoying to have it in the way. I manage to hide it pretty easily via
```css
.vjs-user-inactive{
  cursor: none;
}
```
on my stylus extension.
