### ISSUE TITLE
Slowly get 403s on new install until it doesnt work

### ISSUE THREAD

**Issue by PipeItToDevNull** [omarroth/invidious#813]
When invidious is first stood up on docker I can load the main page, but after interacting with it for a few minutes I can access fewer pages, losing access to `/login` and `/preferences` then to the full site.

**Comment by PipeItToDevNull** [comment]
Docker logs:

```
┌[ssh][groot@geordi.dev0.sh][~]
┕ docker logs invidious_invidious_1 
Unhandled exception:  (DB::ConnectionRefused)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: Cannot establish connection (PQ::ConnectionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: Error connecting to 'postgres:5432': Connection refused (Errno)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Unhandled exception:  (DB::ConnectionRefused)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: role "kemal" does not exist (PQ::PQError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Unhandled exception:  (DB::ConnectionRefused)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: role "kemal" does not exist (PQ::PQError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Unhandled exception:  (DB::ConnectionRefused)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: role "kemal" does not exist (PQ::PQError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Unhandled exception:  (DB::ConnectionRefused)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: Cannot establish connection (PQ::ConnectionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Caused by: Error connecting to 'postgres:5432': Connection refused (Errno)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

**Comment by PipeItToDevNull** [comment]
When inside the invidious container I see this:

```
/invidious # cat config/config.yml
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: postgres
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:
top_enabled: true
captcha_enabled: true
login_enabled: true
registration_enabled: true
/invidious # curl postgres:5432
curl: (52) Empty reply from server
```
