### ISSUE TITLE
Hello why not work get video page data ?

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#840]
Hello why not work get video page data ? I get this errro Video unavailable.
https://mp3lerindir.biz/watch?v=cgeUysHOLKQ
How fix this ? I Thnik this google want captcha issuse 
https://ru-clip.net/video/c3prYnNzy3M/sen-anlat-karadeniz-60-b%C3%B6l%C3%BCm.html and a lot of  other site fix this problem.How fix this problem ? Please help me

**Comment by omarroth** [comment]
Duplicate of #811. If you have IPv6 available for your machine you may try setting `force_resolve: ipv4` or `force_resolve: ipv6`.

**Comment by yaskammm** [comment]
How using force_resolve: ipv6 ? Please help me

**Comment by omarroth** [comment]
In your configuration file `config/config.yml`. Like so:

```yaml
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: xxxx
  host: 127.0.0.1
  dbname: invidious

# ...

force_resolve: ipv6 # <---
```
